# -*- coding: utf-8 -*-
"""c1181.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DwLWKSgeHqhCqUjtHBa6aocq9y3XISD-
"""

from google.colab import files
data_to_load=files.upload()

import pandas as pd
import plotly.express as px
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("stars.csv")
fig=px.scatter(df,x="Size",y="Light")
fig.show()

X=df.iloc[:,[0,1]].values
print(X)
wcss=[]
for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init="k-means++",random_state=42)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)
plt.figure(figsize=(10,5))
sns.lineplot(range(1,11),wcss,marker='o',color='red')
plt.title("The Elbow Method")
plt.xlabel("Number of clusters")
plt.ylabel("WCSS")
plt.show()

kmeans=KMeans(n_clusters=3,init="k-means++",random_state=42)
y_kmeans=kmeans.fit_predict(X) 

plt.figure(figsize=(15,7))
sns.scatterplot(X[y_kmeans==0,0],X[y_kmeans==0,1],color="yellow",label="cluster1")
sns.scatterplot(X[y_kmeans==1,0],X[y_kmeans==1,1],color="red",label="cluster2")
sns.scatterplot(X[y_kmeans==2,0],X[y_kmeans==2,1],color="green",label="cluster3")

sns.scatterplot(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],color="black",label="centroids",s=100,marker=',')
plt.grid(False)
plt.title("Cluster of interstellar objects")
plt.xlabel("Size")
plt.ylabel("Light")
plt.legend()
plt.show()